### ISSUE TITLE
Product Filter Attribute Drag and Drop leads to about:blank in Firefox

### ISSUE THREAD

**Issue by nbjayme** [ergonode/frontend#240]
## Bug type
UI

## Current behavior
On the Product Catalog, I want to create filters by drag and drop of attribute.
Dropping the attribute to the filter box leads to about:blank page of Firefox

## Expected behavior
Attribute will be added into the filter box.

## Environment

Firefox 70.0.1  under Windows 10

**Comment by derpdead** [comment]
Fixed in [release](https://github.com/ergonode/frontend/releases/tag/v0.6.1)
