### ISSUE TITLE
Placeholder text overlaps entry on input field.

### ISSUE THREAD

**Issue by nbjayme** [ergonode/frontend#243]
## Bug type
Styling

## Current behavior
Placeholder label overlaps the entry field. This is observed on slow connection.

## Expected behavior
Placeholder label stays on the background and/or gone when input field has value.

## Possible Solution
Avoid placeholder for now and simply use a text below the input field that will serve
as label for the entry.

## Environment
Firefox 70.x on Windows 10

![placeholder-overlaps](https://user-images.githubusercontent.com/1008389/70059156-3bb70680-161b-11ea-8a9b-3def8f27d0db.png)

**Comment by derpdead** [comment]
Should not occur any more.
