### ISSUE TITLE
Getting CORS issue and Not able to login

### ISSUE THREAD

**Issue by sandeepmaven2408** [ergonode/frontend#314]
Hello Team,

I setup front and back end as per provided instruction. 
Backend is http://ip_address:8000/ https://imgur.com/SSmdvI0
front End is http://ip_address:3333/ https://imgur.com/0QsCG2V
I am getting following errors
Access to XMLHttpRequest at 'http://ip_address:8000/api/v1/login' from origin 'http://ip_address:3333' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'null' that is not equal to the supplied origin.

POST http://ip_address:8000/api/v1/login net::ERR_FAILED
Please help me
Thank you

**Comment by sandeepmaven2408** [comment]
Hi Team
The issue is resolved by allowing specific IP in .env.local file in backend.

**Comment by derpdead** [comment]
Hello, we are glad you made it. Sorry for not replaying ya on time.
