### ISSUE TITLE
Documentation incorrect

### ISSUE THREAD

**Issue by peterjaap** [ergonode/frontend#500]
## Bug type
Documentation

## Current behavior
It states in the docs here; https://docs.ergonode.com/#/frontend/installation?id=configuration

```
Execute CLI command and set you API URL (env):

npm run cli:run
```

However, this command should be `npm run env`

## Possible Solution
Fix docs

## Environment

<pre><code>
Ergonode version: X.Y.Z

 
Detailed information:
- Node version: XX  
- Browser (Version): 
- Platform:  

Others:

</code></pre>

**Comment by derpdead** [comment]
@peterjaap here are updated [docs](https://docs.ergonode.com/#/installation/frontend?id=contribution-installation)
