### ISSUE TITLE
v1.0.0-beta.8 tag is same as v1.0.0-beta.7

### ISSUE THREAD

**Issue by dankempster** [ergonode/frontend#702]
Both `v1.0.0-beta.8` and `v1.0.0-beta.7` tags are applied to commit cda0fda203d6253fd4c58ff946755c17be651fdc.

Shouldn't `v1.0.0-beta.8` (and `v1`?) be applied to commit b0472c9b0baf3b738f8900f1bd361e1e2f33a890 'Release/v1.0.0 beta.8'?

**Comment by bleto** [comment]
Hi @dankempster , great that you noticed that!  👍 

Something was wrong with the tags :P 
Issue already fixed and tag `v1.0.0-beta.8` is up to date.

P.S. Tag `v1` was created by mistake, we removed it. 

Thanks 👍
