### ISSUE TITLE
Cannot connect - Network Error

### ISSUE THREAD

**Issue by ultrajej** [ergonode/frontend#843]
## Bug type
On Linux (K)Ubuntu 20.04 64 bits
I installed both backend and frontend without obvious issue
I type the login and get the message:

---
**Network Error**

---

I don't have much more...

### Backend: 
```shell
bin/console server:run                                                                                                   
 [OK] Server listening on http://127.0.0.1:8000
```
### Frontend:
```erb

 ERROR  HTML validation errors found for /                                                                                                                 html-validate 15:07:08

inline
  1979:6747  error  <fieldset> must have a <legend> as the first child    wcag/h71
  1979:6985  error  <fieldset> must have a <legend> as the first child    wcag/h71
  1979:7515  error  <fieldset> must have a <legend> as the first child    wcag/h71
  1979:8011  error  Element <div> is not permitted as content in <label>  element-permitted-content
  1979:8899  error  <fieldset> must have a <legend> as the first child    wcag/h71
  1979:9103  error  <input> element does not have a <label>               input-missing-label

✖ 6 problems (6 errors, 0 warnings)

More information:
https://html-validate.org/rules/wcag/h71.html
https://html-validate.org/rules/wcag/h71.html
https://html-validate.org/rules/wcag/h71.html
https://html-validate.org/rules/element-permitted-content.html
https://html-validate.org/rules/wcag/h71.html
https://html-validate.org/rules/input-missing-label.html
```

## Input Code
N/A

## Expected behavior
I should login in...

## Possible Solution
Can you let me now witch logs (and their path) may be useful for you?

## Environment

<pre><code>
Ergonode version: git 2021-04-18 (using the dev data set)
- Backend (git describe): 0.1.0-1236-g0766b6b58
- Frontend (git describe):  0.1.0-1360-g83bb1a47
 
Detailed information:
- Node version: v10.19.0
- Browser (Version): Firefox 87.0 (64-bit), Chrome 90.0.4430.72 (64-bit)
- Platform:  Virtual Linux (K)Ubuntu 20.04 64 bits

Others:
I installed default version of packages from the system.

By the way, I also tried the Docker version and I've got the same issue!
</code></pre>

**Comment by derpdead** [comment]
@ultrajej did you configure .env for frontend? https://docs.ergonode.com/#/installation/frontend-development?id=configuration

**Comment by ultrajej** [comment]
@derpdead Thanks, I was only missing the port for the backend... I can access the PIM.

Ergonode looks promising. I will keep an eye on the project.
